services:
  base-service:
    build: .
    container_name: base-service
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - 3333:3333
    networks:
      - ms-network

  redis:
    image: redislabs/redismod:latest
    container_name: ms-redis
    ports:
      - 6379:6379
    volumes:
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.redis/sysctl.conf:/etc/sysctl.conf
      - ./.redis/data:/data
    networks:
      - ms-network

  redis-ui:
    image: redislabs/redisinsight:latest
    container_name: ms-redis-ui
    ports:
      - 8001:8001
    depends_on:
      - redis
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
