services:
  base-service:
    build: .
    image: service-1
    container_name: service-1
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - ms-network

  redis:
    image: redislabs/redismod
    container_name: ms-redis
    ports:
      - 6379:6379
    volumes:
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.redis/sysctl.conf:/etc/sysctl.conf
      - ./.redis/data:/data
    networks:
      - ms-network

  redis-insight:
    image: redislabs/redisinsight:1.13.1
    container_name: ms-redis-insight
    ports:
      - 8001:8001
    depends_on:
      - redis
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge